INSERT INTO user (USERNAME, PASSWORD, ENABLED) VALUES('user','password',TRUE);
INSERT INTO user (USERNAME, PASSWORD, ENABLED) VALUES('admin','password',TRUE);
INSERT INTO user (USERNAME, PASSWORD, ENABLED) VALUES('test1','12345',TRUE);
INSERT INTO user (USERNAME, PASSWORD, ENABLED) VALUES('test2','12345',TRUE);

INSERT INTO authorities (USERNAME,AUTHORITY) VALUES('user','ROLE_USER');
INSERT INTO authorities (USERNAME,AUTHORITY) VALUES('admin','ROLE_ADMIN');
INSERT INTO authorities (USERNAME,AUTHORITY) VALUES('test1','ROLE_USER');
INSERT INTO authorities (USERNAME,AUTHORITY) VALUES('test2','ROLE_USER');

INSERT INTO blog_post (CONTENT,DRAFT,PUBLISHDATE,TITLE,USER_ID)
VALUES ('Test Content Spring MVC',false,NOW(),'test',1);
